base_url: "https://guimig.github.io/EmailBackupHub/"
home_url: "https://sites.google.com/ifc.edu.br/ceof-araquari/inicio"
max_report_age_days: 1

telegram:
  token_env: "TELEGRAM_TOKEN"
  chat_id_env: "TELEGRAM_CHAT_ID"
